### ISSUE TITLE
NAudio does not support VBR(Got a frame at sample rate 16000, in an MP3 with sample rate 44100. Mp3FileReader does not support sample rate changes)

### ISSUE THREAD

**Issue by CQJeffrey** [naudio/NAudio#229] opened 2017-09-02 02:28 UTC
My requirement is "change the channel as 1, bitrate as 32kbps and splite the time span the mp3 file as 2 minuts". 
```
 public static Stream ProcessAudioStream(Stream inputStream)
        {
            Stream fs = new MemoryStream();
            Stream outputStream = new MemoryStream();           
            try
            {                

                Stream tempStream = new MemoryStream(); 

                using (var waveStream = new Mp3FileReader(inputStream))
                using (WaveFileWriter waveFileWriter = new WaveFileWriter(tempStream, new Mp3WaveFormat(44100,1,8,32000)))
                {
                    byte[] bytes = new byte[waveStream.Length];
                    waveStream.Read(bytes, 0, (int)waveStream.Length);
                    waveFileWriter.Write(bytes, 0, bytes.Length);
                    waveFileWriter.Flush();
                    fs = BytesToStream(bytes);
                }
                fs.Position = 0;

                using (var mp3 = new Mp3FileReader(fs))
                //Got a frame at sample rate 16000, in an MP3 with sample rate 44100. Mp3FileReader does not support sample rate changes
                {
                    Mp3Frame frame;
                    while ((frame = mp3.ReadNextFrame()) != null)
                    {
                        if ((int)mp3.CurrentTime.TotalSeconds <= 120)//2 mintues
                        {
                            `outputStream.Write(frame.RawData,` 0, frame.RawData.Length);
                        }
                    }
                }
           }
            catch (Exception e)
            {
                string msg = e.Message;

            }
            return outputStream;
        }

```
Mp3FileReader is throwing an exception: 
**Got a frame at sample rate 16000, in an MP3 with sample rate 44100. Mp3FileReader does not support sample rate changes.**

Would someone give me some suggestions for this error? thanks
In additions, you can click below url to download my source code. Use VS2015 to open the project, thanks.
 https://pan.baidu.com/s/1qYiEqle

My email is 54373175@qq.com 
Let me know if you have any comments for this error.

**Comment by markheath** [comment] 2017-11-18 20:30
This is nothing to do with VBR. What it is is a sample rate change (or more likely some kind of file corruption that NAudio is interpreting as a sample rate change). This is a known bug that is being tracked elsewhere so I am closing this issue.

**Closed by markheath** 2017-11-18 20:30 UTC

**Comment by maricusa08** [comment] 2019-01-17 19:43
> This is nothing to do with VBR. What it is is a sample rate change (or more likely some kind of file corruption that NAudio is interpreting as a sample rate change). This is a known bug that is being tracked elsewhere so I am closing this issue.

Is this bug resolved somewhere else? I have problems trying to parse a file because of this issue with MP3FileReader

**Comment by markheath** [comment] 2019-01-18 09:33
I recommend that you use `MediaFoundationReader` where possible in preference to `Mp3FileReader` which is likely to be much more robust towards malformed or unusual MP3 files.

**Comment by frankpost** [comment] 2019-02-28 20:47
Hello Mark ... regarding the Mp3FileReader issue and your recommendation to use the
MediaFoundationReader currently my application takes in custom encrypted mp3 files and decrypts them into a MemoryStream. This Stream is then passed into the Mp3FileReader. Unfortunately I am receiving too often the InvalidOperationException "Got a frame at sample rate N, in an MP3 with sample rate X. Mp3FileReader does not support sample rate changes." I would like to use the
MediaFoundationReader as you suggest however, the constructor only takes a file path and in the case of my application I do not want to expose non-encrypted mp3 audio files on a hard drive. I have researched how/if the MediaFoundationReader can be modified to use a stream ( IMFByteStream ) but there does not seem to be viable solutions to this. Are you aware of how this can be accomplished?

Thank you for your time Mark.

**Comment by frankpost** [comment] 2019-03-06 21:56
Answer to my own question use StreamMediaFoundationReader to read in a MemoryStream.
Ex: var waveStream = WaveFormatConversionStream.CreatePcmStream(new StreamMediaFoundationReader(ms)

**Comment by markheath** [comment] 2019-03-07 07:09
You don't need the WaveFormatConversionStream - the StreamMediaFoundationReader will already emit PCM

**Comment by mcsSandippatil** [comment] 2021-02-24 18:53
I Need To Convert .Opus to MP3 Other Wise How to play .opus format file

**Comment by RSDNTWK** [comment] 2021-04-07 16:14
Bug is caused by artwork being present in the ID3 Tags. We will open a separate issue.
