### ISSUE TITLE
Strong Name Verification

### ISSUE THREAD

**Issue by shargon** [naudio/NAudio#252] opened 2017-10-18 08:44 UTC
Please add a strong name for this library (Nuget), i cant load this because my app have a sign

**Comment by markheath** [comment] 2017-10-19 15:12
I recommend you just make your own strong named build. Strong naming [brings as many new problems](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md) as it solves.

**Comment by shargon** [comment] 2017-10-21 06:29
I'm not saying it's safe to use StrongName, but it does serve as a signature to verify that this binary comes from where it came from. The fact is that if you had the library Strong name, both users with and without it, could use it, unlike now, which is limited to unsigned programs only.

**Comment by markheath** [comment] 2018-01-23 14:19
duplicate of #182

**Closed by markheath** 2018-01-23 14:19 UTC
